export const GET_ALL_DECKS_SUCCESS = 'GET_ALL_DECKS_SUCCESS'
export const ADD_NEW_DECK_SUCCESS = 'ADD_NEW_DECK_SUCCESS'
export const GET_DECK_SUCCESS = 'GET_DECK_SUCCESS'

export const ADD_NEW_CARD_SUCCESS = 'ADD_NEW_CARD_SUCCESS'